Update 10148
WWDCNotes/Content pull request #422
Opened 2023-08-15 16:53 UTC by multitudes

some more screenshots, links and code blocks. timestamps. 

Still work in progress. Got until widgets, to be continued!

2023-08-17 11:41 UTC, Jeehut approved these changes

2023-08-17 11:41 UTC, Jeehut requested changes

2023-08-17 11:41 UTC, Jeehut commented on .obsidian/app.json
> +{}
Can you please remove these Obsidian files? Thank you.

2023-08-17 14:12 UTC, multitudes commented on .obsidian/app.json
> +{}
ops, sorry, removing now!  

I tried to use obsidian to edit the markdown files but it did not work because their markdown parser did not recognise our way to add images. Quite odd. 
Anyway it is not the right tool for the job because it tries to add and modify my repo! as you see...

2023-08-17 14:14 UTC, multitudes commented on .obsidian/app.json
> +{}
Done! Thanks for spotting this!

2023-08-17 16:43 UTC, multitudes commented
I removed the obsidian files

2023-08-18 06:42 UTC, Jeehut approved these changes
Wow, so detailed, thank you very much! 👍

2023-08-18 06:42 UTC, merged