Explore 3d body pose and person segmentation in vision - WWDC 2023 se…
WWDCNotes/Content pull request #463
Opened 2024-02-04 09:03 UTC by rakeshneela

…ssion

2024-02-09 00:05 UTC, Jeehut requested changes
@rakeshneela Thank you very much! But please make sure to add your GitHub handle at the top. Then I will merge.

2024-02-09 00:44 UTC, rakeshneela commented
@Jeehut I have added it. Please take a look and merge it. Thanks!

2024-02-15 13:12 UTC, Jeehut approved these changes

2024-02-15 13:12 UTC, Jeehut approved these changes
Thank you very much!

2024-02-15 13:13 UTC, merged