add session links and a couple of notes
WWDCNotes/Content pull request #464
Opened 2024-02-27 04:42 UTC by halmueller

Add links to session mentioned ambiguously in talk. Minor additions.

2024-02-27 13:35 UTC, Jeehut requested changes

2024-02-27 13:35 UTC, Jeehut commented on content/notes/wwdc23/10090.md
> +contributors: coughski, halmueller
Please only add yourself in the contributors list for more significant changes.

2024-02-27 13:35 UTC, Jeehut commented on content/notes/wwdc23/10090.md
> +contributors: coughski, halmueller
Please only add yourself in the contributors list for more significant changes.

2024-02-27 13:35 UTC, Jeehut commented on content/notes/wwdc23/10090.md
> +Existing `ARView`s and `ARSession`s need to be rebuilt, won't work on visionOS. See "Re-imagine your ARKit app for spatial experiences [_sic_]" (probably [session 10091](https://developer.apple.com/v
Why does it state "probably" and "maybe"? Why is it unclear?

2024-02-27 13:35 UTC, Jeehut commented on content/notes/wwdc23/10090.md
> +Disabled by default on iPhone and iPad apps. Code sample 07:59.
Not a must, but have you considered adding a direct link to the timecode in the video? I believe timecodes are supported.

2024-02-28 06:23 UTC, halmueller commented on content/notes/wwdc23/10090.md
> +Existing `ARView`s and `ARSession`s need to be rebuilt, won't work on visionOS. See "Re-imagine your ARKit app for spatial experiences [_sic_]" (probably [session 10091](https://developer.apple.com/v
Text updated, if you wondered why then other people will too.

2024-02-28 07:37 UTC, Jeehut approved these changes

2024-02-28 07:37 UTC, merged

2024-02-28 07:37 UTC, Jeehut commented
@halmueller Awesome, thank you for this!